# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-transcriptcorral-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.2
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.1.1
  - conda-forge::pygments=2.8.1
  
  # Software dependencies
  - conda-forge::pandas=1.2.3
  - conda-forge::numpy=1.20.2
  - conda-forge::xmltodict=0.12.0
  - conda-forge::tbb=2020.2
  - bioconda::sra-tools=2.10.0